#!/bin/bash -ex

# NOTE: this script is only served https://ci.deepin.io/job/rr-checker-lava-bridge.
# Don't use it directly.

# the caller need pass $CHANGE_LIST in

function find_job_name()
{
    if [[ $JOB_NAME != "auto" ]]; then
	echo $JOB_NAME
	return
    else
	set +e
	for checker in $(ls ./jobs/*.auto); do
	    if [[ $(bash $checker $CHANGE_LIST) ]]; then
		bname=$(basename $checker)
		echo "${bname/.auto/}"
		return
	    fi
	done
	set -e
    fi
}

JOB_NAME="$(find_job_name)"
if [[ $JOB_NAME == "" ]]; then
    echo "Can't find valid JOB_NAME"
    exit -1
fi

python -u ./lava-output-wrap.py $JOB_NAME

last_result=$?

if [[ $last_result == 0 ]]; then
    result="true"
else
    result="false"
fi

source params.env

set +x  # Must use this to hide the $RR_CHECKER_TOKEN value
curl -X POST ${HOST_API}/test_result/${REVIEW_ID} -H "Access-Token: $RR_CHECKER_TOKEN" -d "comment=lava bridge. see details in ${BUILD_URL}/console&passed=$result"

if [[ $result != "true" ]]; then
    exit 1
fi
